name: macOS Big Sur (11) Recovery ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone OpenCorePkg (for macrecovery.py)
        run: |
          git clone https://github.com/acidanthera/OpenCorePkg.git
          mkdir -p /tmp/BigSurRecovery

      - name: Patch macrecovery.py to avoid TTY errors
        run: |
          # Replace terminal size check with a fixed fallback to prevent OSError
          sed -i '' 's/os.get_terminal_size().columns/80/' OpenCorePkg/Utilities/macrecovery/macrecovery.py

      - name: Download macOS Big Sur Recovery
        run: |
          cd OpenCorePkg/Utilities/macrecovery

          echo "🔍 Forcing macOS Big Sur (11.x) recovery image..."
          # iMac20,1 board ID (Big Sur-capable Mac)
          python macrecovery.py -b Mac-E43C1C25D4880AD6 -m 00000000000000000 download

          echo "✅ Download complete. Moving files to /tmp/BigSurRecovery"
          mv *.dmg /tmp/BigSurRecovery/ || true
          mv *.chunklist /tmp/BigSurRecovery/ || true

          echo "📂 Recovery files:"
          ls -lh /tmp/BigSurRecovery

      - name: Compress Recovery Files into ZIP
        run: |
          cd /tmp/BigSurRecovery
          echo "📦 Creating ZIP archive..."
          zip -r9 /tmp/macOS_BigSur_Recovery.zip *
          ls -lh /tmp/macOS_BigSur_Recovery.zip

      - name: Upload macOS Big Sur Recovery ZIP
        uses: actions/upload-artifact@v4
        with:
          name: macOS-BigSur-Recovery
          path: /tmp/macOS_BigSur_Recovery.zip
          compression-level: 9
